name: Technomath
favicon: null
layout_spectrum: 0.8508298920933157
typography_spectrum: 0.9726340593770146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.02722331741824746
  lightness: 0.6929504780564457
  saturation: 0.2352049055043608
  rhythmicContrast: 0.9840772841125727
purpose: []
